# Generated by Django 3.1.4 on 2021-03-08 10:23

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(db_column='kullanicikod', max_length=20, unique=True, verbose_name='User Username')),
                ('password', models.TextField(db_column='sifre', verbose_name='Password')),
                ('registry_number', models.CharField(blank=True, db_column='sicilno', max_length=12, null=True, verbose_name='User Registry Number')),
                ('fullname', models.CharField(db_column='adsoyad', max_length=50, verbose_name='Name and Surname')),
                ('bolumkod', models.CharField(blank=True, max_length=5, null=True, verbose_name='Department Code')),
                ('is_active', models.BooleanField(db_column='aktif', verbose_name='User activity status')),
                ('authority', models.BooleanField(blank=True, db_column='yetki', null=True, verbose_name='Authorization Level')),
                ('theme', models.CharField(blank=True, db_column='tema', max_length=30, null=True)),
                ('is_superuser', models.BooleanField(db_column='admin', verbose_name='Is Admin Level?')),
                ('date_joined', models.DateTimeField(db_column='olusturmatarih')),
                ('temsilci', models.BooleanField(blank=True, null=True)),
                ('email', models.TextField(db_column='emailaddr', verbose_name='Email Address of User')),
                ('localelang', models.CharField(blank=True, max_length=5, null=True)),
                ('tammenu', models.BooleanField(blank=True, null=True)),
                ('dashboardstr', models.TextField(blank=True, null=True)),
                ('dashudsgroupids', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), size=None)),
                ('dashudsseverities', django.contrib.postgres.fields.ArrayField(base_field=models.BooleanField(blank=True, null=True), size=None)),
            ],
            options={
                'db_table': 'kullanici',
                'ordering': ['id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MailDefinition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('definition', models.TextField(blank=True, null=True)),
                ('tosubject', models.TextField(blank=True, null=True)),
                ('anomalytypes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'maildefinition',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MailingList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('touser', models.TextField(blank=True, null=True)),
                ('tosubject', models.TextField(blank=True, null=True)),
                ('creationdate', models.DateTimeField(blank=True, null=True)),
                ('senddate', models.DateTimeField(blank=True, null=True)),
                ('tocontent', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'maillist',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MailUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userdesc', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mailusers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Menus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menuname', models.CharField(blank=True, max_length=50, null=True)),
                ('menutip', models.CharField(blank=True, max_length=2, null=True)),
                ('formid', models.BigIntegerField(blank=True, null=True)),
                ('ustmenu', models.BigIntegerField(blank=True, null=True)),
                ('sira', models.IntegerField(blank=True, null=True)),
                ('link', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'menuler',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SystemUsersRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roleid', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'kullanicirol',
                'managed': False,
            },
        ),
    ]
