# Generated by Django 3.1.4 on 2021-03-08 10:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReportBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField(blank=True, null=True, verbose_name='User ID that select this report type')),
                ('user_group', models.IntegerField(blank=True, null=True, verbose_name='Group ID for licence over user groups')),
                ('report_name', models.TextField(blank=True, null=True, verbose_name='Name that given by user')),
                ('report_format', models.TextField(blank=True, null=True, verbose_name='List formatted report details')),
                ('report_type', models.TextField(blank=True, null=True, verbose_name='List formatted report type details')),
                ('visual_format', models.TextField(blank=True, null=True, verbose_name='Text formatted visual format details')),
                ('home_page', models.BooleanField(default=False, verbose_name='Do you want to see this on your home page?')),
                ('mailing_interval', models.IntegerField(blank=True, null=True, verbose_name="Email sending interval by days, if null ve don't send email")),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name="Exact date & time report's creation")),
            ],
            options={
                'ordering': ['-id', 'user_group', 'user', 'home_page'],
                'unique_together': {('user', 'report_format')},
            },
        ),
    ]
